name: Bug report
about: Report a bug to help us improve
title: "[BUG] "
labels: bug
assignees: ""

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node version
      placeholder: "e.g. 20.x"
